name: HMEasyCore
version: '${project.version}'
main: net.heavenmine.hmezcore.Main
authors: [ FuxWa ]
description: This plugin made by HeavenMine Team
website: heavenmine.net
commands:
  gm:
    description: Change your game mode
  broadcast:
    description: Send massage to all player !
    aliases:
      - bc
  feed:
    description: Feed a player
  heal:
    description: Heal a player
  ec:
    description: Open enderchest
  inventory:
    description: Open inventory
    aliases:
      - inv
  god:
    description: Enable god mode
